Todo_List/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('todo-admin/', admin.site.urls),
    path('', include('Todo_List_App.urls'))
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

Todo_List_App/models.py
from django.contrib.auth.models import AbstractUser , User
from django.db import models
from django.utils import timezone
from django.conf import settings
from datetime import timedelta
import os
from django.utils.deconstruct import deconstructible
from .utils import resize_image
from cryptography.fernet import Fernet

def get_fernet_key():
    return settings.FERNET_KEY

fernet = Fernet(get_fernet_key())

class CustomUser(AbstractUser):
    email = models.EmailField(unique=True)
    firstName = models.CharField(max_length=30, default='Name1')
    lastName = models.CharField(max_length=30, default='Name2')
    phone = models.CharField(max_length=15, default='0123456789')
    address = models.CharField(max_length=180, default='Earth')
    email_verified = models.BooleanField(default=False)
    encrypted_id = models.CharField(max_length=256, blank=True, editable=False, unique=True)
    
    def save(self, *args, **kwargs):
        if self.pk is None and not self.encrypted_id:
            super().save(*args, **kwargs)
            self.encrypted_id = fernet.encrypt(str(self.id).encode()).decode()
            super().save(update_fields=['encrypted_id'])
        else:
            super().save(*args, **kwargs)
    
    def __str__(self):
        return self.username
    
    @staticmethod
    def encrypt_id(user_id):
        return fernet.encrypt(str(user_id).encode()).decode()
    
    @staticmethod
    def decrypt_id(encrypted_id):
        return int(fernet.decrypt(encrypted_id.encode()).decode())
    
class PasswordResetRequest(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, null=True)
    timestamp = models.DateTimeField(auto_now_add=True)
    reset_link_used = models.BooleanField(default=False)
    reset_link_expiry = models.DateTimeField(null=True, blank=True)
    reset_link_generated_at = models.DateTimeField(null=True, blank=True)

    email_verification_limit = models.PositiveIntegerField(default=5) 
    email_verification_timestamp = models.DateTimeField(null=True, blank=True)

    @staticmethod
    def email_verification_limit_reached(user, limit, duration):
        time_threshold = timezone.now() - timedelta(minutes=duration)
        recent_verifications = PasswordResetRequest.objects.filter(
            user=user,
            email_verification_timestamp__gt=time_threshold
        )
        if recent_verifications.count() >= limit:
            first_verification_time = recent_verifications.earliest('email_verification_timestamp').email_verification_timestamp
            remaining_time = duration - int((timezone.now() - first_verification_time).total_seconds() // 60)
            return True, remaining_time
        return False, None
    
    @staticmethod
    def request_limit_reached(user, limit, duration):
        user_id = CustomUser.decrypt_id(user.encrypted_id)
        time_threshold = timezone.now() - timedelta(minutes=duration)
        recent_requests = PasswordResetRequest.objects.filter(user_id=user_id, timestamp__gt=time_threshold)
        if recent_requests.count() >= limit:
            first_request_time = recent_requests.earliest('timestamp').timestamp
            remaining_time = duration - int((timezone.now() - first_request_time).total_seconds() // 60)
            return True, remaining_time
        return False, None

    def save(self, *args, **kwargs):
        if not self.reset_link_expiry:
            self.reset_link_expiry = timezone.now() + timedelta(minutes=20)
        super().save(*args, **kwargs)


class Task(models.Model):
    HIGH = 'High'
    MEDIUM = 'Medium'
    LOW = 'Low'
    PENDING = 'Pending'
    COMPLETED = 'Completed'
    OVERDUE = 'Overdue'
    IMPORTANCE_CHOICES = [
        (HIGH, 'High'),
        (MEDIUM, 'Medium'),
        (LOW, 'Low'),
    ]
    STATUS_CHOICES = [
        (PENDING, 'Pending'),
        (COMPLETED, 'Completed'),
        (OVERDUE, 'Overdue'),
    ]
    taskTitle = models.CharField(max_length=100)
    description = models.TextField(null = True, blank = True, max_length=500)
    category = models.ForeignKey('Category', related_name='tasks', on_delete=models.CASCADE, null=True)
    dueDate = models.DateTimeField(db_column = 'duedate')
    completedDate = models.DateTimeField(null=True, blank=True)
    createdDate = models.DateTimeField(default=timezone.now)
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, null=True)
    important = models.CharField(
        max_length=6,
        choices=IMPORTANCE_CHOICES,
        default=LOW,
    )
    status = models.CharField(
        max_length=9,
        choices = STATUS_CHOICES,
        default=PENDING
        )
    notificationTime = models.IntegerField(default=4)
    sent_reminder = models.BooleanField(default=False)
    emailNotification = models.BooleanField(default=False)
    encrypted_id = models.CharField(max_length=256, blank=True, editable=False, unique=True)

    def save(self, *args, **kwargs):
        is_new = self.pk is None
        super().save(*args, **kwargs)
        if is_new:
            self.encrypted_id = fernet.encrypt(str(self.id).encode()).decode()
            super().save(update_fields=['encrypted_id'])

    def __str__(self):
        return self.taskTitle

    @staticmethod
    def decrypt_id(encrypted_id):
        return int(fernet.decrypt(encrypted_id.encode()).decode())

class Category(models.Model):
    name = models.CharField(max_length=50, default='Others')
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, null=True)

    def __str__(self):
        return self.name
    
    def task_count(self):
        return self.tasks.count()

class CompletedTask(models.Model):
    task = models.OneToOneField(Task, on_delete=models.CASCADE)
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, null=True)

    def __str__(self):
        return self.task.taskTitle

@deconstructible
class PathAndRename:
    def __init__(self, path):
        self.path = path

    def __call__(self, instance, filename):
        ext = filename.split('.')[-1]
        
        username = instance.user.username

        count = instance.profile_picture_change_count
        filename = f'pp_{username}_{count}.{ext}'
        
        return os.path.join(self.path, str(instance.user.id), filename)


class Profile(models.Model):
    GENDER_CHOICES = [
        ('Male', 'Male'),
        ('Female', 'Female'),
        ('None', 'Rather not say'),
        ('Other', 'Other'),
    ]
    user = models.OneToOneField(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    profilePicture = models.ImageField(upload_to=PathAndRename('profile_pictures'), default='default.png')
    profile_picture_change_count = models.PositiveIntegerField(default=0)
    completedTasksCount = models.PositiveIntegerField(default=0)
    enableEmailNotifications = models.BooleanField(default=False)
    bio = models.TextField(max_length=230, blank=True, default='Searching for the meaning of life')
    gender = models.CharField(max_length=10, choices=GENDER_CHOICES, default='None')
    
    def update_completed_tasks_count(self):
        self.completedTasksCount = self.user.task_set.filter(completed=True).count()
        self.save()
    # check if old picture is default or another
    # if another , then it will be remove and add the new picture
    # with a custom file name after resizing using PIL
    def save(self, *args, **kwargs):
        if self.pk:
            old_profile = Profile.objects.get(pk=self.pk)
            if old_profile.profilePicture and old_profile.profilePicture.name != self.profilePicture.name:
                if old_profile.profilePicture.name != 'default.png':
                    old_profile.profilePicture.delete(save=False)
                
                self.profile_picture_change_count += 1
                self.profilePicture = resize_image(self.profilePicture)
        else:
            if self.profilePicture:
                self.profilePicture = resize_image(self.profilePicture)
            
        super().save(*args, **kwargs)

    def __str__(self):
        return self.user.username


class Solve(models.Model):
    username = models.CharField(max_length=100)
    email = models.EmailField()

class Notifications(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, null=True)
    name = models.CharField(max_length=200, default='This is a notification')
    date = models.DateTimeField(default=timezone.now)
    unread = models.BooleanField(default=True)
    notificationsCount = models.PositiveIntegerField(default=0)

    def __str__(self):
        return self.name

    @classmethod
    def unread_count(cls, user):
        user_id = CustomUser.decrypt_id(user.encrypted_id)
        return cls.objects.filter(user_id=user_id, unread=True).count()

templates/base.html
{% load static %}

<link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}">
<link href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.7.2/font/bootstrap-icons.css" rel="stylesheet">
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
<link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
<link rel="icon" type="image/png" href="{% static 'favicon/favicon.ico' %}">
<style>
    .nav-link .notificationIcon {
        opacity : 1 !important;
        color : #FEFEFE;
        font-size : 20px;
        margin-top : 5px;
        padding-bottom : -10px;
    }
    .nav-link.active {
        opacity: 1;
    }
    .dropdown-menu {
        .dark-mode & {
            background-color : #333 !important;
            .dropdown-item {
                .dark-mode & {
                    color : white !important;
                }
            }
            &:hover .dropdown-item {
                background-color : #333;
                color : white;
            }
            .activeDropdown {
                background-color : #444 !important;
            }
        }
        .activeDropdown {
            background-color : #f8f9fa !important;
        }
    }
    .dark-mode{
        .form-check-label {
            color : white !important;
        }
        .dropdown-divider {
            border-top : 1px solid #444 !important;
        }
    }
</style>
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
    <div class="container-fluid">
        <a class="navbar-brand" href="/home">
            <img src="/static/background/todo.png" class="rounded-circle" width="30" height="30" alt="todo">
        </a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNavDropdown">
            <ul class="navbar-nav">
                <li class="nav-item">
                    {% if user.is_authenticated %}
                        <a class="nav-link {% if request.path == "/tasks/create/" %}active{% endif %}" aria-current="page" href="/tasks/create">Create</a>
                    {% else %}
                        <a class="nav-link" aria-current="page" href="{% url 'signin' %}?next=/tasks/create">Home</a>
                    {% endif %}
                </li>
                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle {% if request.path == "/tasks/running/" or request.path == "/tasks/completed/" %}active{% endif %}" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                        Tasks
                    </a>
                    <ul class="dropdown-menu">
                        <li class="nav-item">
                            {% if user.is_authenticated %}
                                <a class="dropdown-item {% if request.path == "/tasks/running/" %}activeDropdown{% endif %}" aria-current="page" href="/tasks/running"style="border-bottom:1px solid #444;">
                                    <span class="textGlow">Running</span>
                                </a>
                            {% else %}
                                <a class="dropdown-item" aria-current="page" href="{% url 'signin' %}?next=/tasks/running">Running</a>
                            {% endif %}
                        </li>
                        <li class="nav-item">
                            {% if user.is_authenticated %}
                                <a class="dropdown-item {% if request.path == "/tasks/completed/" %}activeDropdown{% endif %}" aria-current="page" href="/tasks/completed">Completed</a>
                            {% else %}
                                <a class="dropdown-item" aria-current="page" href="{% url 'signin' %}?next=/tasks/completed">Completed</a>
                            {% endif %}
                        </li>
                    </ul>
                </li>
                <li class="nav-item">
                    {% if user.is_authenticated %}
                        <a class="nav-link {% if request.path == "/categories/add/" or request.path == "/categories/all/" %}active{% endif %}" aria-current="page" href="/categories/all">Category</a>
                    {% else %}
                        <a class="nav-link" aria-current="page" href="{% url 'signin' %}?next=/categories/all">Category</a>
                    {% endif %}
                </li>
                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                        Download
                    </a>
                    <ul class="dropdown-menu">
                        <li class="nav-item">
                            {% if user.is_authenticated %}
                                <a class="dropdown-item" aria-current="page" href="/tasks/export/pdf"style="border-bottom:1px solid #444;">Export as PDF</a>
                            {% else %}
                                <a class="dropdown-item" aria-current="page" href="{% url 'signin' %}?next=/tasks/export/pdf/">Export as PDF</a>
                            {% endif %}
                        </li>
                        <li class="nav-item">
                            {% if user.is_authenticated %}
                                <a class="dropdown-item" aria-current="page" href="/tasks/export/csv">Export as CSV</a>
                            {% else %}
                                <a class="dropdown-item" aria-current="page" href="{% url 'signin' %}?next=/tasks/export/csv/">Export as CSV</a>
                            {% endif %}
                        </li>
                    </ul>
                </li>
            </ul>
            <ul class="navbar-nav ms-auto">
                <li class="nav-item">
                    <div class="notificationIcon">
                        {% if user.is_authenticated %}
                        <a class="nav-link" href="/notifications">
                            {% if unread_count > 0 %}
                                <i class="material-icons notificationIcon"title="New Notifications!">notifications_active</i>
                            {% else %}
                                <i class="material-icons notificationIcon"title="No New Notifications!">notifications</i>
                            {% endif %}
                        </a>
                        {% else %}
                        <a class="nav-link" href="{% url 'signin' %}?next=/notifications">
                            <i class="material-icons notificationIcon"title="No New Notifications!">notifications</i>
                        </a>
                        {% endif %}
                    </div>
                </li>
                <li class="nav-item dropdown">
                {% if user.is_authenticated %}
                    <a class="nav-link dropdown-toggle no-caret" href="#" id="userDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                        <img src="{{ user.profile.profilePicture.url }}" class="rounded-circle altPic" width="25" height="25" alt="Profile Picture">
                    </a>
                    <ul class="dropdown-menu dropdown-menu-end" aria-labelledby="userDropdown">
                        <li>
                            <div class="dropdown-header">
                                <img src="{{ user.profile.profilePicture.url }}" class="rounded-circle" width="30" height="30" alt="Profile Picture">
                                {{ user.username }}
                            </div>
                        </li>
                        <li><hr class="dropdown-divider"></li>
                        <li>
                            {% if user.is_authenticated %}
                                <a class="dropdown-item {% if request.path == "/account/" %}activeDropdown{% endif %}" href="/account/">
                                    <i class="bi bi-person-fill"></i>  Profile
                                </a>
                            {% else %}
                                <a class="dropdown-item {% if request.path == "/account/" %}activeDropdown{% endif %}" href="{% url 'signin' %}?next=/account">
                                    <i class="bi bi-person-fill"></i>  Profile
                                </a>
                            {% endif %}
                        </li>
                        <li><hr class="dropdown-divider"></li>
                        <li>
                            <a class="dropdown-item" href="https://github.com/NAHIAN-19/Todo-List-Django">
                                <i class="bi bi-info-circle-fill"></i>   About
                            </a>
                        </li>
                        <li><hr class="dropdown-divider"></li>
                        <li>
                            <label class="form-check-label" for="themeIcon" id="themeChange" style="margin-left:15px;user-select: none;">
                                <i id="themeIcon" class="bi" style="cursor: pointer;"></i>
                                Dark Mode
                            </label>
                        </li>
                        <li><hr class="dropdown-divider"></li>
                        <li>
                            <a class="dropdown-item" href="{% url 'logout' %}">
                                <i class="bi bi-door-closed-fill"></i>  Logout
                            </a>
                        </li>
                    </ul>
                {% else %}
                    <a class="nav-link dropdown-toggle" href="#" id="userDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                        User
                    </a>
                    <ul class="dropdown-menu dropdown-menu-end" aria-labelledby="userDropdown">
                        <li><hr class="dropdown-divider"></li>
                        <li>
                            <a class="dropdown-item" href="/signin">
                                <i class="bi bi-person-fill"></i>
                                    Sign In
                            </a>
                        </li>
                        <li><hr class="dropdown-divider"></li>
                            <li>
                            <a class="dropdown-item" href="/signup">
                                <i class="bi bi-person-plus-fill"></i>
                                    Sign Up
                            </a>
                        </li>
                        <li><hr class="dropdown-divider"></li>
                        <li>
                            <label class="form-check-label" for="themeSwitch" id="themeChange" style="margin-left:15px;user-select: none;">
                                <i id="themeIcon" class="bi" style="cursor: pointer;"></i>
                                Dark Mode
                            </label>
                        </li> 
                    </ul>
                {% endif %}
                </li>
            </ul>
        </div>
    </div>
</nav>
<script>
    const darkModePref = localStorage.getItem('darkMode');
    const themeIcon = document.getElementById('themeChange');

    function updateThemeIcon(isDarkMode) {
        if (isDarkMode) {
            themeIcon.classList.remove('bi-sun-fill');
            themeIcon.classList.add('bi-moon-fill');
            themeIcon.style.color = 'black';
        } else {
            themeIcon.classList.remove('bi-moon-fill');
            themeIcon.classList.add('bi-sun-fill');
            themeIcon.style.color = 'black';
        }
    }

    if (darkModePref === 'true') {
        document.body.classList.add('dark-mode');
        updateThemeIcon(true);
    } else {
        updateThemeIcon(false);
    }

    themeIcon.addEventListener('click', function () {
        const isDarkMode = document.body.classList.toggle('dark-mode');
        localStorage.setItem('darkMode', isDarkMode);
        updateThemeIcon(isDarkMode);
    });
</script>

templates/generatePDF.html
{% load static %}
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-KK94CHFLLe+nY2dmCWGMq91rCGa5gtU4mk92HdvYe+M/SXH301p5ILy+dN9+nJOZ" crossorigin="anonymous">
    <link rel="icon" type="image/png" href="{% static 'favicon/favicon.ico' %}">
    <title>Task Report</title>
    <style>
        body {
            font-family: Arial, Helvetica, sans-serif;
            font-size: 14px;
            margin: 0;
            padding: 0;
        }
        h1 {
            text-align: center;
        }
        table {
            border-collapse: collapse;
            width: 100%;
        }
        th, td {
            text-align: center;
            padding: 8px;
            word-wrap: break-word;
            max-width: 150px;
            word-break: break-all;
            white-space: normal;
        }
        th {
            background-color: #f2f2f2;
            border: 1px solid #888;
            text-align: center;
        }
        .total-task {
            text-align: center;
            font-size: 20px;
            font-weight: bold;
            margin-top: 20px;
        }
        .profile-table {
            margin: 20px auto;
            border-collapse: separate;
            border-spacing: 10px;
            border: none;
        }
        .profile-table td {
            padding: 10px;
            border: 1px solid #ddd;
            background-color: #f9f9f9;
        }
        .profile-image {
            border-radius: 50%;
            max-width: 200px;
            max-height: 200px;
            border: 5px solid #fff;
            box-shadow: 0 4px 8px rgba(0, 0, 0, 0.1);
            display: flex;
            margin: auto;
        }
        .des {
            font-size: 14px;
            text-align: center;
            margin-top: 5px;
            font-weight: bold;
            margin-bottom: 5px;
        }
        .task-group {
            page-break-inside: avoid;
            margin-bottom: 10px;
        }
        .taskTable {
            border-spacing: 0;
            border-collapse: collapse;
        }
        .taskTable td, .taskTable th {
            border: 1px solid #000;
        }
        .group_ {
            page-break-inside: avoid;
        }
        .group_ table {
            width: 100%;
            border-spacing: 0;
            border-collapse: collapse;
        }
        .group_ table th, .group_ table td {
            border: 1px solid #000;
        }
        .profile-table td.info {
            text-align: left;
            white-space: pre-wrap;
        }
    </style>
</head>
<body>
    <h1>Task Report of || {{ user.username }} ||</h1>
    {% if profile_picture_base64 %}
        <table class="profile-table">
            <tr>
                <td rowspan="5"><img class="profile-image" src="data:image/png;base64,{{ profile_picture_base64 }}"></td>
                <td class="info"><strong>Username  : </strong> {{ user.username }}</td>
            </tr>
            <tr>
                <td class="info"><strong>Full Name : </strong> {{ user.firstName }} {{ user.lastName }}</td>
            </tr>
            <tr>
                <td class="info"><strong>Email     : </strong> {{ user.email }}</td>
            </tr>
            <tr>
                <td class="info">{% if user.phone %}<strong>Phone     : </strong> {{ user.phone }}{% else %}<strong>Phone:</strong> Not Available{% endif %}</td>
            </tr>
            <tr>
                <td class="info">{% if user.address %}<strong>Address   : </strong> {{ user.address }}{% else %}<strong>Address:</strong> Not Available{% endif %}</td>
            </tr>
        </table>
    {% endif %}
    <div>
        <p class="total-task"><strong>Total Tasks: {{ tasks|length }}</strong></p>
    </div>
    <table class="taskTable">
        <tr>
            <th scope="col" colspan="5">Title</th>
        </tr>
        <tr>
            <th scope="col" colspan="5">Category</th>
        </tr>
        <tr>
            <th scope="col">Created Date</th>
            <th scope="col">Due Date</th>
            <th scope="col">Completed Date</th>
            <th scope="col">Important</th>
            <th scope="col">Status</th>
        </tr>
        {% for task in tasks %}
            <tr class="task-group group_">
                <div style="page-break-inside:avoid;position:relative;">
                    <table class="taskTable" border="1">
                        <tr class="task-group group_">
                            <td colspan="5">{{ task.taskTitle }}</td>
                        </tr>
                        <tr class="task-group group_">
                            <td colspan="5">{{ task.category.name }}</td>
                        </tr>
                        <tr class="task-group group_">
                            <td>
                                <center>
                                {{ task.createdDate | date:"d-m-y" }}<br>
                                {{ task.createdDate | date:"h:i A" }}
                                </center>
                            </td>
                            <td>
                                <center>
                                {{ task.dueDate | date:"d-m-y" }}<br>
                                {{ task.dueDate | date:"h:i A" }}
                                </center>
                            </td>
                            <td>
                                <center>
                                {% if task.completedDate %}
                                    {{ task.completedDate | date:"d-m-y" }}<br>
                                    {{ task.completedDate | date:"h:i A" }}
                                {% else %}
                                    <b> N/A </b>
                                {% endif %}
                                </center>
                            </td>
                            <td><center>{{ task.get_important_display }}</center></td>
                            <td>{{ task.get_status_display }}</td>
                        </tr>
                        <tr class="task-group group_">
                            <td colspan="5">
                                <div class="des">Description</div>
                                <div style="text-align:center;">{{ task.description }}</div>
                            </td>
                        </tr>
                    </table>
                <div>
            </tr>    
        {% endfor %}
    </table>
</body>
</html>

templates/home.html
{% load static %}
<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Todo List - Home</title>
    <link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}">   
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css">
    <link rel="stylesheet" href="https://pro.fontawesome.com/releases/v5.10.0/css/all.css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0-beta3/css/all.min.css">
    <link rel="icon" type="image/png" href="{% static 'favicon/favicon.ico' %}">
    <style>
        .container {
            top: 95%;
            left: 50%;
            transform: translate(-50%, -95%);
            position: absolute;
        }
        .jumbotron {
            background-color: rgba(255, 255, 255, 0.8);
            padding: 3rem;
            border-radius: 10px;
            box-shadow: 0 2px 4px rgba(0, 0, 0, 0.2);
        }
        dark-mode .jumbotron {
            background-color: white;
            color: white;
        }
        .title {
            font-size: 3rem;
            font-weight: bold;
            color: #333;
            margin-bottom: 1.5rem;
        }
        .description {
            font-size: 1.5rem;
            color: #555;
            margin-bottom: 2rem;
        }
        .btn-get-started {
            background-color:blue;
            border-color: black;
            font-size: 1.25rem;
            font-weight: bold;
            padding: 0.75rem 1.5rem;
        }
        .row i {
            color: black;
        }
        .dark-mode .row i {
            color: white;
        }
    </style> 
</head>
<body>
    {% include 'base.html' %}
    <div class="jumbotron text-center">
        <h1 class="title">Todo List</h1>
        <p class="description">Stay organized and get things done with our simple and efficient Todo list app.</p>
        {% if user.is_authenticated %}
            <a href="/createTask" class="btn btn-primary btn-get-started">Get Started</a>
        {% else %}
            <a href="/signin" class="btn btn-primary btn-get-started">Get Started</a>
        {% endif %}
    </div>
    <div class="container">
        <div class="row">
            <div class="col-lg-6 mx-auto d-flex flex-column align-items-center justify-content-end">
                <h5 class="section-heading">Contact Us</h5>
                <br>
                <div class="row mb-0">
                    <div class="col d-flex align-items-center">
                        <a href="mailto:nahiannazeeb19@gmail.com">
                            <i class='fas fa-envelope' style='font-size:30px'></i>
                        </a>
                    </div>
                    <div class="col d-flex align-items-center">
                        <a href="https://t.me/n4h14n" target="_blank" class="text-decoration-none">
                            <i class="fab fa-telegram"style="font-size:30px;"></i>
                        </a>
                    </div>
                    <div class="col d-flex align-items-center">
                        <a href="https://www.linkedin.com/in/nahiannazeeb/" target="_blank" class="text-decoration-none"><i class="fab fa-linkedin fa-2x"></i></a>
                    </div>
                </div>
            </div>
        </div>
    </div>
    
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.bundle.min.js" integrity="sha384-geWF76RCwLtnZ8qwWowPQNguL3RmwHVBC9FhGdlKrxdiJJigb/j/68SIy3Te4Bkz" crossorigin="anonymous"></script>
</body>
</html>